### ISSUE TITLE
Problem with json parser

### ISSUE THREAD

**Issue by pragmaticivan** [Accenture/alexia-starter-kit#1] opened 2016-11-27 09:41 UTC
I just tested the example and it's returning this error: `Uncaught error: Cannot read property 'application' of undefined`

Body:

```
{
   "version":"1.0",
   session:{
      "new":true,
      "sessionId":"amzn1.echo-api.session.abeee1a7-aee0-41e6-8192-e6faaed9f5ef",
      "attributes":{

      },
      application:{
         "applicationId":"amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe"
      },
      "user":{
         "userId":"amzn1.account.AM3B227HF3FAM1B261HK7FFM3A2"
      }
   },
   "request":{
      "type":"LaunchRequest",
      "requestId":"amzn1.echo-api.request.9cdaa4db-f20e-4c58-8d01-c75322d6c423"
   }
}
```

**Comment by Glogo** [comment] 2016-11-27 09:58
Your request is not a valid JSON. Try sending this request:

```json
{
   "version":"1.0",
   "session":{
      "new":true,
      "sessionId":"amzn1.echo-api.session.abeee1a7-aee0-41e6-8192-e6faaed9f5ef",
      "attributes":{

      },
      "application":{
         "applicationId":"amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe"
      },
      "user":{
         "userId":"amzn1.account.AM3B227HF3FAM1B261HK7FFM3A2"
      }
   },
   "request":{
      "type":"LaunchRequest",
      "requestId":"amzn1.echo-api.request.9cdaa4db-f20e-4c58-8d01-c75322d6c423"
   }
}
```

If that doesn't help you, could you be more more specific on how you tested the example and where did you get the request?

Also if you are using Postman to send the request (or any other REST client), make sure to send it as "raw" request in application/json format.

**Comment by pragmaticivan** [comment] 2016-11-27 10:27
It was an error from the client. Sorry about that.


I get this weird behavior on Amazon console, and maybe is an issue with the lib:

I have the app running here: https://wedeploy-echo.ivansjr.com/

When I test using the console "hello" I get an error from the server, looks like amazon is sending a json that the lib doesn't parse:

<img width="830" alt="screen shot 2016-11-27 at 2 26 19 am" src="https://cloud.githubusercontent.com/assets/301291/20647432/ec5b59ec-b448-11e6-89f4-34bbcb024a0d.png">


But if I copy the generated json in the text format to the JSON tab, that works:

<img width="850" alt="screen shot 2016-11-27 at 2 27 02 am" src="https://cloud.githubusercontent.com/assets/301291/20647435/015a7ea4-b449-11e6-948e-46b919915010.png">

**Comment by Glogo** [comment] 2016-11-27 15:15
Since your app also listens on GET requests, I assume you configured your http server manually.

Make sure you are trying to handle json request and _not_ request of type string (but I think you just fixed that)

```javascript
const someHandler = (request, response) => {
  // request.payload needs to be object
  app.handle(request.payload, data => {  
    response(data);
  });
};
```

Does the problem with Service Simulator persists? I tested your app url for `HelloIntent` and it is working for me fine

**Comment by pragmaticivan** [comment] 2016-11-28 04:04
So, I'm using the code of this starter kit: https://wedeploy-alexa.herokuapp.com/

In this link. Getting the same behavior while testing with the Amazon panel.

**Comment by Glogo** [comment] 2016-11-28 08:13
This is weird since I can't reproduce the issue and the Amazon Service Simulator is working fine for me

This may help me:
- Could you send me screenshot of the each skill config page? Interaction model, configuration, etc.
- Did you change the starter kit code in any way? If yes what are the changes?
- How did you deploy it to heroku?

Thanks!

**Comment by pragmaticivan** [comment] 2016-11-28 19:50
- Repo: https://github.com/pragmaticivan/wedeploy-alexa (I'm using the assets generated on starter kit).
- I didn't change anything so I could test exactly with what you have.
- Just pushed to heroku using git remote = heroku.
<img width="833" alt="screen shot 2016-11-28 at 11 49 15 am" src="https://cloud.githubusercontent.com/assets/301291/20683411/b8f7baa0-b560-11e6-8003-15d71351971a.png">


If I type hello, that doesn't work.

<img width="848" alt="screen shot 2016-11-28 at 11 49 42 am" src="https://cloud.githubusercontent.com/assets/301291/20683443/dafd0506-b560-11e6-88c4-03e5027c8470.png">

If I copy the json generated by the "hello" into the JSON tab, it works.
<img width="816" alt="screen shot 2016-11-28 at 11 49 52 am" src="https://cloud.githubusercontent.com/assets/301291/20683454/e7530896-b560-11e6-9569-4a2984f896a2.png">

**Comment by Glogo** [comment] 2016-11-29 10:27
I think your issue could be caused by [Dyno Sleeping](https://devcenter.heroku.com/articles/free-dyno-hours#dyno-sleeping).

Try sending the request repeatedly or enter your Heroku server url to browser to make sure it wakes up before testing. 

When you use Free Tier on Heroku, your dyno is put to sleep after 30 minutes of inactivity. Therefore after sending the request again (using the manual JSON input in your case) that worked for you. This free tier is suitable only for development and demos.

**Comment by pragmaticivan** [comment] 2016-11-29 16:17
I don't think that's the problem, because I did run one time manually just in case. And started testing using Amazon dashboard.

**Comment by ohmyjersh** [comment] 2016-12-07 16:28
I'm also seeing application of undefined, deployed to heroku and followed the exact instructions.  @Glogo you get this to work?

**Comment by Glogo** [comment] 2016-12-07 16:43
You are getting this error (probably) because your request probably is not valid JSON (or it is a JSON string). As far as I know the Alexa Service Simulator always produces `application/json` request

I will update alexia to detect the type of request payload and to handle also JSON strings.

**Comment by pragmaticivan** [comment] 2016-12-07 16:52
I started doing this path @Glogo but didn't have time to fix. I actually made it work for a bit applying a conversion in the hapi layer before sending to alexia.

**Comment by ohmyjersh** [comment] 2016-12-07 16:56
When I try to start up the app, I see that it sends back the 'Welcome to alexia startup kit' but when I try to invoke the intent I get nothing but 'Welcome to alexia startup kit' --- so I am wondering if it's not making mapping through.

**Comment by Glogo** [comment] 2016-12-07 17:00
@ohmyjersh have you entered the sample utterances and intent schema into your skill's interaction model?

**Comment by Glogo** [comment] 2016-12-07 17:16
I just updated alexia to version 2.2.3 and added support for handling requests with string payload.
alexia-starter-kit is updated as well to use the latest alexia version

Accenture/alexia#39

please let me know if you are still experiencing the described issues

**Comment by ohmyjersh** [comment] 2016-12-07 17:21
That fixed the parsing issue! thanks!  

So I guess I have a workflow problem, I'm using Alexia for a hackathon.... so I'm just doing it quick and dirty.  But I have setup the invocation to be 'what up' and my utterance is 'I need cash money'.

Should I tell Alexa 'What up' and immediately after 'I need cash money' or just all at once?

**Comment by Glogo** [comment] 2016-12-07 17:39
You have following options:

**First option**
- "Alexa, what up"
*Wait until she stops speaking*
- "I need cash money"

Make sure your session stays open by implementing the `app.onStart` handler by setting `end: false` in responseObject. Alternatively you can set it globally `app.setShouldEndSessionbyDefault(false)`. Then make sure to create some intent that ends session otherwise you will have infinite conversation with Alexa (yay)

**Second Option**
- "Alexa, what up I need cash money"

This would make more sense if your invocation name is something like `my app`. Then you could say:

- "Alexa, tell my app that I need cash money"

See [Official Amazon docs](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/supported-phrases-to-begin-a-conversation) for more detailed explanation

**Comment by ohmyjersh** [comment] 2016-12-07 17:55
nm, got it to work... thanks guys.   I think a gitter chat would be something useful in the future, if you would be interested in setting one up.

**Comment by Glogo** [comment] 2016-12-07 19:26
That's cool idea, I will try to setup gitter soon.

Glad it works for you, I'm closing this issue

**Closed by Glogo** 2016-12-07 19:26 UTC
